

def do_phase_1(story:str):

    #1- METODO CHE DALLA STORIA GENERA LA LORE E SALVA LA LORE

    #2 - GENERIAMO I FILE PDDL DALLA LORE E CREA I FILE DOMAIN E  PROBLEM

    #3. VALIDAZIONE DOMAIN E PROBLEM E GENERAZIONE STORY.JSON

    pass